import { PLACEMENTS, chartLimitation } from '../colorwork/model.js';
import { garmentSuggestions } from '../colorwork/adjustments.js';
export const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function chartGrid(chart,editable=false) {
 return `<div class="chart-scroll"><div class="pixel-chart ${editable?'editable':''}" style="--cols:${chart.width}">${[...chart.cells].reverse().map((row,i)=>`<span class="row-number">${chart.height-i}</span>${[...row].reverse().map((color,j)=>editable?`<button class="pixel" style="--pixel:${chart.palette[color]}" data-pixel="${chart.height-1-i},${chart.width-1-j}" aria-label="Row ${chart.height-i}, stitch ${chart.width-j}, color ${String.fromCharCode(65+color)}"></button>`:`<span class="pixel" style="--pixel:${chart.palette[color]}" title="Color ${String.fromCharCode(65+color)}"></span>`).join('')}`).join('')}<span></span>${Array.from({length:chart.width},(_,i)=>`<span class="column-number">${chart.width-i}</span>`).join('')}</div></div><p class="quiet">${chart.width} stitches × ${chart.height} rows · 1 cell = 1 stitch × 1 row<br>Read from bottom right. ${chart.repeatHorizontal?'Outer edges mark one horizontal repeat.':'One centered motif; background remains the base color.'}</p>`;
}
const swatches=(d,value,attr)=>`<div class="studio-swatches">${d.palette.map((c,i)=>`<button class="swatch ${value===c.hex?'active':''}" style="--swatch:${c.hex}" ${attr}="${i}" aria-label="${esc(c.name)} ${c.hex}" aria-pressed="${value===c.hex}"></button>`).join('')}</div>`;
export function studio(d,p,v,state) {
 const z=d.zones.find(z=>z.placement===state.placement),report=v.zones.find(r=>r.id===z?.id);
 const types=[['solid','Solid','○'],['stripes','Stripes','≋'],['block','Color blocks','◧'],['chart','Custom chart','▦']];
 return `<div class="section-heading"><span class="eyebrow">04 / YOUR COLOR STORY</span><h2>A little color. All you.</h2><p>Build a palette, choose a part of your sweater, then make your mark.</p></div>
 <div class="studio-palette"><h3>Your palette</h3><p class="quiet">A is your base color. Colors are independent of yarn.</p><div class="palette-list">${d.palette.map((c,i)=>`<div class="palette-chip"><label><span>${String.fromCharCode(65+i)} · ${esc(c.name)}</span><input type="color" data-palette="${i}" value="${c.hex}" aria-label="Pick color ${String.fromCharCode(65+i)}"></label><input class="hex" data-hex="${i}" value="${c.hex}" maxlength="7" aria-label="HEX color ${String.fromCharCode(65+i)}" pattern="#[0-9a-fA-F]{6}"></div>`).join('')}</div><button class="text-button" data-color-action="add-color" ${d.palette.length>=12?'disabled':''}>+ Add a color</button></div>
 <h3>Where will it go?</h3><div class="zone-tabs" role="group" aria-label="Pattern zone">${Object.entries(PLACEMENTS).map(([key,item])=>`<button data-zone="${key}" aria-pressed="${state.placement===key}" class="${state.placement===key?'selected':''}">${item.label}${d.zones.some(z=>z.placement===key)?'<i aria-hidden="true">●</i>':''}</button>`).join('')}</div><p class="quiet">${PLACEMENTS[state.placement].note}</p>
 <div class="pattern-types">${types.map(([type,label,glyph])=>`<button class="choice ${z?.type===type?'selected':''}" data-pattern-type="${type}" aria-pressed="${z?.type===type}" ${type==='chart'&&chartLimitation(state.placement)?'disabled aria-describedby="chart-limit"':''}><span aria-hidden="true">${glyph}</span><strong>${label}</strong></button>`).join('')}</div>${chartLimitation(state.placement)?`<p class="quiet" id="chart-limit">${chartLimitation(state.placement)}</p>`:''}
 ${!z?'<div class="studio-note">This zone uses the entire-sweater design, or your base color. Choose a style above to override it.</div>':''}
 ${z&&['solid','block'].includes(z.type)?`<h3>${PLACEMENTS[z.placement].label} color</h3>${swatches(d,z.color,'data-zone-color')}`:''}
 ${z?.type==='stripes'?`<div class="stripe-list">${z.stripes.map((s,i)=>`<div class="stripe-row"><span class="stripe-number">${i+1}</span><select data-stripe-color="${i}" aria-label="Stripe ${i+1} color" style="border-left:12px solid ${s.color}">${d.palette.map(c=>`<option value="${c.hex}" ${c.hex===s.color?'selected':''}>${esc(c.name)} · ${c.hex}</option>`).join('')}</select><label><input type="number" min="1" max="64" step="1" data-stripe-rows="${i}" value="${s.rows}"> rows</label><button data-stripe-up="${i}" ${i===0?'disabled':''} aria-label="Move stripe ${i+1} up">↑</button><button data-stripe-down="${i}" ${i===z.stripes.length-1?'disabled':''} aria-label="Move stripe ${i+1} down">↓</button><button data-stripe-delete="${i}" ${z.stripes.length===1?'disabled':''} aria-label="Remove stripe ${i+1}">×</button></div>`).join('')}</div><button class="text-button" data-color-action="add-stripe" ${z.stripes.length>=8?'disabled':''}>+ Add stripe</button><p class="quiet">Repeat ${z.stripes.map(s=>s.rows).join(' + ')} rows throughout this zone. Each construction section starts the sequence again.</p>`:''}
 ${z?.type==='chart'?`<div class="chart-editor"><div class="number-grid"><label>Width · stitches<input type="number" min="1" max="32" step="1" data-chart-size="width" value="${z.chart.width}"></label><label>Height · rows<input type="number" min="1" max="32" step="1" data-chart-size="height" value="${z.chart.height}"></label></div><p class="quiet">1–32 in each direction. Resizing keeps the bottom-right cells; reducing the size removes cells beyond the new edges.</p><div class="studio-swatches">${d.palette.map((c,i)=>`<button class="swatch ${state.ink===i?'active':''}" style="--swatch:${c.hex}" data-ink="${i}" aria-label="Draw with color ${String.fromCharCode(65+i)}" aria-pressed="${state.ink===i}"></button>`).join('')}</div><div class="chart-tools">${['draw','erase','fill'].map(tool=>`<button data-tool="${tool}" aria-pressed="${state.tool===tool}" class="${state.tool===tool?'selected':''}">${tool[0].toUpperCase()+tool.slice(1)}</button>`).join('')}<button data-color-action="clear-chart">Clear chart</button></div>${chartGrid(z.chart,true)}<label class="checkbox"><input type="checkbox" data-repeat ${z.chart.repeatHorizontal?'checked':''}> Repeat horizontally around the section</label><p class="quiet">One vertical band, placed after separation or in the first suitable straight sleeve interval. Erase returns cells to color A.</p></div>
 ${report?.stitchCount?`<div class="repeat-status ${report.ok?'valid':'invalid'}"><strong>${report.ok?'✓ '+(z.chart.repeatHorizontal?'Perfect repeat':'Single motif fits'):'Pattern needs an adjustment'}</strong><p>${report.stitchCount} stitches ÷ ${z.chart.width} = ${report.repeat.repeats} repeats + ${report.repeat.remainder} remaining</p><small>Chart rounds ${report.startRound}–${report.endRound}; ${report.availableRows} stable rounds available.</small></div>`:''}
 ${report?.errors.map(e=>`<p class="error">${esc(e)}</p>`).join('')||''}
 ${garmentSuggestions(p,d,z.id).length?`<div class="adjustments"><h3>Keep the chart, adjust the fit?</h3><p class="quiet">Current bust ${p.finished.bust.toFixed(1)} cm · upper arm ${p.finished.upperArm.toFixed(1)} cm. Nothing changes until you choose an option. Every option is checked again against shaping, ribbing and all color zones.</p>${garmentSuggestions(p,d,z.id).map((o,i)=>`<div class="adjustment"><strong>${o.stitches} section stitches · ${o.measurement.toFixed(1)} cm</strong><p>${o.measureLabel}: ${o.garmentMeasurement.toFixed(1)} cm${o.ease!=null?` · +${o.ease.toFixed(1)} cm ease`:''}</p><button class="secondary" data-apply-adjustment="${i}" ${o.allowed?'':'disabled'}>Use this fit</button>${!o.allowed?`<small>${esc(o.reason)}</small>`:''}</div>`).join('')}</div>`:''}`:''}
 ${z?'<button class="text-button" data-color-action="remove-zone">Remove this zone override</button>':''}
 ${d.zones.length?`<details><summary>${d.zones.length} active color zones</summary>${d.zones.map(z=>`<p>${PLACEMENTS[z.placement].label} · ${z.type}</p>`).join('')}<p>Specific zones override Entire sweater. A chart zone uses the base color outside its chart band.</p></details>`:''}
 ${p.design.bustTarget!==null||p.design.upperArmTarget!==null?`<div class="studio-note">Custom fit applied: bust target ${p.design.bustTarget??'standard'} cm · upper-arm target ${p.design.upperArmTarget??'standard'} cm. <button class="text-button" data-color-action="reset-fit">Restore standard fit</button></div>`:''}
 <p class="quiet" id="save-status">${esc(state.saveStatus)}</p><button class="text-button" data-color-action="download-design">Download design data</button>`;
}
