const cm = n => `${n.toFixed(1)} cm`;
const rows = a => a.join(', ') || 'none';

/** Neckline-specific instructions replace the circular crew setup where necessary. */
export function applyNecklineInstructions(p, sections) {
  const n = p.neckline, d = p.design, f = p.finished;
  const rib = d.rib === '1x1' ? 'knit 1, purl 1' : 'knit 2, purl 2';
  if (!n.isV) {
    const descriptions = {
      crew: 'This classic round opening uses the crew-neck cast-on allocation.',
      wideCrew: 'This wider round opening uses a larger cast-on and broader front/back allocation; do not substitute the crew-neck count.',
      mock: 'Work the collar at full height and wear it standing upright; do not fold it.',
      turtle: `The ${cm(f.neckband)} collar is knitted at full height. Fold it outward in half when worn for approximately ${cm(f.neckband / 2)} visible height. Do not sew the fold shut.`,
      boat: 'This shallow boat opening uses a wider front/back allocation and a low ribbed edge. Do not add the crew-neck short rows.',
    };
    sections[1].title = `01 · ${n.label}${['mock','turtle'].includes(d.neckline) ? ' collar' : ' edge'}`;
    sections[1].text = `${descriptions[d.neckline]}\n\n${sections[1].text}`;
    if (d.neckline === 'boat') sections[3] = { title: '03 · Keep the boat opening shallow', text: 'There are no short rows for this neckline. The front and back have the same length and the broad opening sits symmetrically. Begin the yoke at round 1 immediately after the neckband.' };
    return sections;
  }

  sections[0].text += ' For this V-neck, also swatch stockinette worked flat; it must match the circular gauge. The neckline band is picked up after the body and sleeves, and only its two short ends are secured at the V point.';
  sections[1] = { title: '01 · Cast on the open V-neck yoke', text: `Cast on ${p.castOn} stitches. Do not join and do not knit a neckband yet. The front starts with only 1 stitch on each side of the opening. The missing ${n.neckAdded} front stitches will be added along the V edges while the raglan grows. This cast-on is for stockinette worked flat, so it does not need to fit the neckband rib repeat. Arrange the work with the right side facing for row 1; cast-on itself does not count as a row.` };
  sections[2] = { title: '02 · Mark the open-yoke sections', text: `From the first front edge, arrange: 1 front stitch; marker, 1 raglan stitch, marker; ${p.initial.sleeve} sleeve stitches; marker, 1 raglan stitch, marker; ${p.initial.back} back stitches; marker, 1 raglan stitch, marker; ${p.initial.sleeve} sleeve stitches; marker, 1 raglan stitch, marker; 1 front stitch. Place a distinctive centre-back marker halfway across the back. Move stitches to place markers without working an extra row. Total: ${p.castOn} stitches. Keep the outer front edges free of raglan markers.` };
  sections[3] = { title: '03 · Shape the V while working the raglan', text: `The following flat rows are the FIRST ${n.flatRows} rows of the yoke schedule in step 04, not extra rows. Work odd-numbered right-side rows knit and even-numbered wrong-side rows purl. Work ${n.neckSchedule.length} pairs of neckline increases on these right-side rows: ${rows(n.neckSchedule)}.\n\nOn each listed neckline row, cast on 1 stitch at the beginning AND 1 stitch at the end with a backward-loop cast-on. Knit/purl these new stitches normally on subsequent rows. These edge additions are separate from the raglan increases and add 2 stitches per listed row. Using edge cast-ons avoids trying to make two lifted increases from the same strand when the front has only one stitch. Never add neckline stitches on other rows.\n\nAfter flat row ${n.flatRows} (a wrong-side row), turn to the right side. On row ${n.flatRows + 1}, knit across the entire yoke, working any scheduled raglan increases, then join the two front edges into a round without casting on extra stitches. Place a temporary round-start marker at the V point. Keep counting subsequent full rounds from this front marker until all ${p.yokeRounds} yoke rows/rounds are complete. The opening is approximately ${cm(f.vDepth)} deep from the back-neck base. The combined fronts have now received all ${n.neckAdded} missing stitches. No German short rows or separate resolution round are used.` };
  sections[4] = { title: '04 · Follow the raglan schedule', text: `Count ${p.yokeRounds} yoke rows/rounds in total, including all flat rows and the joining round described in step 03. Do not restart the counter after joining. On BODY increase rows/rounds, add 1 stitch on the body side of each raglan line: one at the raglan end of each separate front while flat (two at the ends of the combined front once joined), and one at each end of the back. This adds 4 stitches total. On SLEEVE increase rows/rounds, add 1 stitch at each end of both sleeve sections, adding 4 total. A row in both schedules adds 8 raglan stitches; if also listed for neckline shaping, it adds another 2 at the outer front edges.\n\nKeep each single raglan stitch between its two markers. Make a left-leaning lifted increase at a section start and a right-leaning lifted increase at a section end. Lift the strand front-to-back and knit its back leg for left-leaning; lift back-to-front and knit its front leg for right-leaning. All scheduled flat increases are on right-side rows. Purl wrong-side rows without increases. Once joined, knit every unlisted round plain.\n\nBody increase rows/rounds (${p.bodyIncreases}): ${rows(p.bodySchedule)}.\n\nSleeve increase rows/rounds (${p.sleeveIncreases}): ${rows(p.sleeveSchedule)}.\n\nAt the end: combined front ${p.frontEnd}, back ${p.backEnd}, each sleeve ${p.sleeveEnd}, plus 4 raglan stitches = ${p.yokeTotal} stitches. Yoke depth from the back-neck base: ${cm(f.yoke)}. Try on and confirm the V depth and underarm fit before continuing. Keep the front round-start marker in place for the separation round.` };
  // Start the separation round at the actual round origin; no uncounted repositioning.
  sections[5] = { title: '05 · Separate body and sleeves', text: `Beginning at the V-point round marker, knit ${p.frontEnd / 2} front stitches and the next raglan stitch. Hold the next ${p.sleeveEnd} sleeve stitches on waste yarn. Cast on ${p.underarm} underarm stitches. Knit the next raglan stitch, all ${p.backEnd} back stitches, and the following raglan stitch. Hold the second ${p.sleeveEnd} sleeve stitches and cast on ${p.underarm} more underarm stitches. Knit the last raglan stitch and the remaining ${p.frontEnd / 2} front stitches. All four raglan stitches stay on the body: ${p.bodyStitches} stitches total. Remove the raglan and centre-back markers; keep the front round-start marker. This separation round counts as body round 1.` };
  sections[6].text = sections[6].text.replaceAll('below the neckband', 'from the back-neck base/shoulder datum').replace('Neckband height is additional.', 'Measure vertically from the shoulder-level back-neck base, not from the V point.');
  const ribRows = d.rib === '1x1'
    ? 'Every row: knit 1 edge stitch, repeat knit 1, purl 1 across the interior, knit 1 edge stitch.'
    : 'Right-side rows: knit 1 edge stitch, repeat knit 2, purl 2 across the interior, knit 1 edge stitch. Wrong-side rows: knit 1 edge stitch, repeat knit 2, purl 2 across the interior as viewed from that side, knit 1 edge stitch.';
  sections.splice(8, 0, { title: '08 · Pick up the crossover V band', text: `After both sleeves are complete, return to the neck opening. With right side facing, start at the V point. Pick up and knit ${n.pickupEachSide} stitches evenly along the first sloping edge, then ${p.castOn} along the original cast-on edge, then ${n.pickupEachSide} down the other sloping edge to the V point. Total: ${n.neckbandStitches} stitches. Do not join the band in the round. The first and last stitch are garter-stitch selvedges; the remaining ${n.neckbandStitches - 2} stitches fit the ${d.rib} repeat.\n\nThe pickup pass is setup and is not included in the band rows. Turn and work ${p.neckbandRounds} rows of flat rib. ${ribRows} Knit the selvedges on both sides. Bind off loosely in pattern. The band is approximately ${cm(f.neckband)} wide. Overlap its two short ends at the V point, keeping the right-front end on top, and sew each short end neatly to the opposite sloping neckline edge with a yarn tail. Do not sew the neck opening closed. This creates a crossover V finish without centre decreases.\n\nThe pickup count is based on the calculated edge length and your gauge. Check that the band lies flat before securing the ends; unusual yarn or edge tension may require physical fitting beyond this mathematical model.` });
  sections.at(-1).title = '09 · Second sleeve and finishing';
  // Both sleeves must precede the band, so make the order explicit.
  sections[7].title = '07 · Both sleeves';
  sections[7].text += '\n\nRepeat this entire sleeve instruction for the second sleeve before working the neckline band.';
  sections.at(-1).text = sections.at(-1).text.replace('Work the second sleeve exactly as the first, using the same decrease schedule. ', '').replace('below the neckband', 'from the back-neck base/shoulder datum');
  sections.at(-1).title = '09 · Finishing';
  return sections;
}
