import { validateResult } from './calculate.js';
import { applyNecklineInstructions } from './neckline-pattern.js';

const cm = n => `${n.toFixed(1)} cm`;
const rounds = a => a.length ? a.join(', ') : 'none';

/** Prose is a deterministic view of validated numbers; never another calculator. */
export function makePattern(p) {
  if (!p.ok || validateResult(p).length) throw new Error('A valid calculation is required.');
  const d = p.design, f = p.finished;
  const rib = d.rib === '1x1' ? 'knit 1, purl 1' : 'knit 2, purl 2';
  const sections = [
    { title: 'Before you begin', text: `Wash and dry a stockinette swatch knitted in the round. Your gauge must be ${d.stitchGauge} stitches and ${d.rowGauge} rounds per 10 cm. Use ${d.needle} mm needles, or the size that achieves this gauge. Also swatch the ${d.rib} rib; its relaxed gauge may differ. You need circular needles suitable for the neck and body, a small-circumference method for sleeves, 9 markers (one distinctive), waste yarn and a tapestry needle. Yarn: ${d.yarn || 'your chosen yarn'}. ${p.yarnEstimate ? `Rough yarn budget from your swatch mass: ${p.yarnEstimate.grams} g, rounded up to ${p.yarnEstimate.balls} balls (${p.yarnEstimate.meters} m). This area estimate includes 15% allowance; confirm with a comparable sweater and buy enough of one dye lot.` : 'Yarn quantity is not guessed from gauge. Enter the dry weight of a 10 × 10 cm swatch in advanced settings for a rough material budget.'}` },
    { title: '01 · Neckband', text: `Loosely cast on ${p.castOn} stitches using a stretchy cast-on. Check that the edge stretches comfortably over your head. Join in the round without twisting and place the distinctive beginning-of-round marker at centre back. Work ${p.neckbandRounds} rounds of ${rib}, repeated around. The neckband is approximately ${cm(f.neckband)} high. All ribbed counts are divisible by ${p.repeat}.` },
    { title: '02 · Mark the raglan sections', text: `From centre back, arrange stitches as follows: ${p.initial.back / 2} back stitches; marker, 1 raglan stitch, marker; ${p.initial.sleeve} sleeve stitches; marker, 1 raglan stitch, marker; ${p.initial.front} front stitches; marker, 1 raglan stitch, marker; ${p.initial.sleeve} sleeve stitches; marker, 1 raglan stitch, marker; ${p.initial.back / 2} remaining back stitches. The eight markers bracket the four single raglan stitches. Move stitches between needles to place markers without knitting an extra round. Total: ${p.castOn}.` },
    { title: '03 · Raise the back neckline', text: p.shapingPairs ? `Work 3 pairs of German short rows without any increases. Starting at centre back with the right side facing, knit across the half-back and raglan stitch, then 2 stitches into the first sleeve; turn and make a double stitch. Purl back across the back and the opposite raglan stitch, then 2 stitches into the other sleeve; turn and make a double stitch. Repeat the pair, turning after the 4th original sleeve stitch on each side, then repeat turning after the 6th original sleeve stitch on each side. Resolve any double stitch you encounter as one stitch. After the last turn and double stitch, knit to centre back. Work 1 full knit round, resolving remaining double stitches. This resolution round is separate from the yoke schedule. The back gains 6 local rows (${cm(6 / (d.rowGauge / 10))}) while the front gains none from the short rows. To make a German double stitch: after turning, bring yarn forward, slip the first stitch purlwise, then pull yarn firmly up and over the needle so both legs appear; move yarn as needed for the next knit or purl stitch. When resolving, knit or purl both legs together as one stitch.` : 'Short-row shaping is switched off. This makes a symmetric neckline with no back rise; front and back sit at the same height. Continue directly with the yoke.' },
    { title: '04 · Shape the raglan yoke', text: `Reset the round counter to 1. Work ${p.yokeRounds} rounds in stockinette (knit every stitch in the round). Keep each raglan stitch as one stitch. On BODY increase rounds, make one stitch just inside each end of the front and back sections: 4 new stitches in total. On SLEEVE increase rounds, make one stitch just inside each end of each sleeve section: 4 new stitches in total. A round listed in both schedules adds 8 stitches. Make a left-leaning increase at each section start and a right-leaning increase at each section end; keep these increases outside the paired markers bracketing the raglan stitches. For a left-leaning increase, lift the strand between stitches from front to back and knit through its back leg. For a right-leaning increase, lift it from back to front and knit through its front leg. On all unlisted rounds knit without increases.\n\nBody increase rounds (${p.bodyIncreases}): ${rounds(p.bodySchedule)}.\n\nSleeve increase rounds (${p.sleeveIncreases}): ${rounds(p.sleeveSchedule)}.\n\nAt the end: front ${p.frontEnd}, back ${p.backEnd}, each sleeve ${p.sleeveEnd}, plus 4 raglan stitches = ${p.yokeTotal} stitches. Front yoke depth below the neckband, including the shaping resolution round: ${cm(f.yoke)}. Try on before separation. If depth or circumference needs changing, recalculate rather than inserting unscheduled increases.` },
    { title: '05 · Separate body and sleeves', text: `From centre back, knit ${p.backEnd / 2} back stitches and the next raglan stitch. Place the next ${p.sleeveEnd} sleeve stitches on waste yarn, excluding the raglan stitches. Cast on ${p.underarm} underarm stitches. Knit the next raglan stitch, all ${p.frontEnd} front stitches, and the following raglan stitch. Hold the second set of ${p.sleeveEnd} sleeve stitches and cast on another ${p.underarm} underarm stitches. Knit the final raglan stitch and the remaining ${p.backEnd / 2} back stitches. Remove the eight raglan markers; keep the centre-back marker. All four raglan stitches remain on the body. You now have ${p.bodyStitches} body stitches. This separation round counts as body round 1 below.` },
    { title: '06 · Body and hem', text: `Including the separation round just worked, knit ${p.bodyPlain} body rounds total with no shaping (${p.bodyPlain - 1} more rounds after separation). Then work ${p.hemRounds} rounds of ${rib} for the hem and bind off loosely in pattern. Count ${p.bodyStitches} stitches throughout. Finished front length below the neckband: ${cm(f.bodyLength)}, including the ${cm(f.hem)} hem. Back length below the neckband: ${cm(f.backLength)}. Neckband height is additional.` },
    { title: '07 · First sleeve', text: `Return ${p.sleeveEnd} held stitches to needles. With right side facing and new yarn, begin at the centre of the underarm cast-on edge. Pick up and knit ${p.underarm / 2} stitches along the first half, knit the held sleeve stitches, then pick up and knit ${p.underarm / 2} along the remaining half. Place a beginning-of-round marker at underarm centre: ${p.upperArmStitches} stitches. This pickup round is sleeve round 1. Close corner gaps later with a yarn tail rather than adding unscheduled stitches.\n\nWork ${p.sleevePlain} stockinette rounds total, counting the pickup round. On these rounds decrease 2 stitches: ${rounds(p.decreaseSchedule)}. To decrease, knit 1, knit 2 together, knit to the last 3 stitches, slip 2 stitches separately knitwise and knit them together through their back loops, knit 1. All other rounds are plain knit. After ${p.decreases} decrease rounds, exactly ${p.cuffStitches} stitches remain.\n\nWork ${p.cuffRounds} rounds of ${rib}, then bind off loosely in pattern. Sleeve length from underarm, including the ${cm(f.cuffLength)} cuff: ${cm(f.sleeveLength)}. The cuff measures approximately ${cm(f.cuff)} at the entered gauge, before rib contraction.` },
    { title: '08 · Second sleeve and finishing', text: `Work the second sleeve exactly as the first, using the same decrease schedule. Close any underarm corner gaps with the yarn tails. Weave in ends, wash according to the yarn instructions, and dry flat to the finished measurements. Do not stretch ribbing aggressively. Check bust ${cm(f.bust)}, upper arm ${cm(f.upperArm)} and front length ${cm(f.bodyLength)} below the neckband. This generated design has mathematical checks but has not been physically test-knitted; fit also depends on yarn behaviour and personal proportions.` },
  ];
  return { title: `The everyday raglan · ${d.size} · ${p.neckline.label}`, sections: applyNecklineInstructions(p, sections) };
}

export function patternText(p) {
  const pattern = makePattern(p), f = p.finished;
  return `PURL STUDIO\n${pattern.title}\n\nFinished bust ${cm(f.bust)} · ease +${cm(f.ease)}\nFront length ${cm(f.bodyLength)} ${p.neckline.isV ? 'from back-neck base/shoulder datum' : 'below neckband'} · sleeve ${cm(f.sleeveLength)} from underarm\nUpper arm ${cm(f.upperArm)} · cuff ${cm(f.cuff)}\n\n${p.warnings.map(w => `NOTE: ${w.text}`).join('\n')}\n\n${pattern.sections.map(s => `${s.title}\n${s.text}`).join('\n\n')}\n`;
}
